### PR TITLE
Really make it a library

### PR DESCRIPTION
**Pull request by cyrilmottier**
The main idea is to clean things up. Using the AppsFlyer SDK ends up in having a bunch of resources (drawables, colors, etc.) and AndroidManifest.xml (`android:supportsRtl`, etc.) attributes getting added to the client project for nothing.

cf commit messages for more information

### CODE REVIEW

**Comment by cyrilmottier** [comment]
Does anyone is still maintaining this project?

**Comment by af-fess** [comment]
Hi @cyrilmottier .Thank you for your efforts.
It makes sense.
we will test your changes on next few days and will merge

Thank you

**Comment by cyrilmottier** [comment]
Thanks for the feedback @af-fess. Looking forward to hear about your tests and potential merge.

**Comment by cyrilmottier** [comment]
Great! Thanks 👍  Is a release on Maven expected soon?

**Comment by af-fess** [comment]
@cyrilmottier hope today/tomorow will push it. we have additional changes
Thanks,

**Comment by af-fess** [comment]
on maven http://repo1.maven.org/maven2/com/appsflyer/segment-android-integration/1.10/

**Comment by cyrilmottier** [comment]
Thank you 👍

**Pull request merged**
